version: '1'

services:
  app:
    image: 'rbc-test:latest'
    build:
      context: .
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - PG_DB_URL=jdbc:postgresql://db:5432/postgres
      - PG_DB_USER=postgres
      - PG_DB_PASS=postgres

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres